'use strict';

// ══ CATÁLOGO PRINCIPAL ════════════════════════════════════════════
const BOOKS = [
    /* ── FANTASÍA (6) ── */
    {id:1,title:"El nombre del viento",author:"Patrick Rothfuss",genre:"Fantasía",subgenre:"Fantasía épica",price:22.90,originalPrice:32.00,isbn:"0756404746",badge:"Bestseller",rating:4.9,reviews:8432,pages:662,language:"Español",publisher:"Debolsillo",year:2007,color:"linear-gradient(135deg,#8B2635 0%,#3d0f18 100%)",description:"Kvothe, el mago más temido y famoso de su época, vive escondido bajo un nombre falso como posadero en un pueblo olvidado. Cuando Cronista lo encuentra, Kvothe acepta narrar su historia en tres días. Una prosa de belleza extraordinaria.",shortDesc:"Un mago recuenta su vida épica en esta monumental obra de fantasía.",tags:["Magia","Universidad","Aventura","Épico"]},
    {id:7,title:"Harry Potter y la piedra filosofal",author:"J.K. Rowling",genre:"Fantasía",subgenre:"Fantasía juvenil",price:17.90,originalPrice:25.00,isbn:"0439708184",badge:"Icónico",rating:4.9,reviews:45231,pages:309,language:"Español",publisher:"Salamandra",year:1997,color:"linear-gradient(135deg,#722F37 0%,#1a0a0d 100%)",description:"Harry Potter ha vivido bajo la escalera de casa de sus tíos sin saber que es un mago. En Hogwarts descubrirá que es famoso por haber sobrevivido al ataque del temible Voldemort cuando era bebé. El inicio de la saga más leída de la historia.",shortDesc:"El inicio de la saga mágica más leída de la historia.",tags:["Magia","Escuela","Amistad","Aventura"]},
    {id:9,title:"El señor de los anillos",author:"J.R.R. Tolkien",genre:"Fantasía",subgenre:"Fantasía épica",price:29.90,originalPrice:42.00,isbn:"0618640150",badge:"Legendario",rating:4.9,reviews:38910,pages:1216,language:"Español",publisher:"Minotauro",year:1954,color:"linear-gradient(135deg,#3a5c1a 0%,#0f1f05 100%)",description:"En la Tierra Media, el hobbit Frodo Bolsón hereda el Anillo Único, forjado por el Señor Oscuro Sauron. Con la ayuda de la Compañía del Anillo, emprende un peligroso viaje hacia Mordor para destruir el Anillo en el Monte del Destino.",shortDesc:"La obra cumbre de la fantasía épica que lo inició todo.",tags:["Épico","Mitología","Aventura","Clásico"]},
    {id:17,title:"El camino de los reyes",author:"Brandon Sanderson",genre:"Fantasía",subgenre:"Fantasía épica",price:24.90,originalPrice:35.00,isbn:"0765326353",badge:"Epic Fantasy",rating:4.9,reviews:21543,pages:1007,language:"Español",publisher:"Nova",year:2010,color:"linear-gradient(135deg,#1a3550 0%,#08141e 100%)",description:"En el mundo de Roshar, devastado por las tormentas de alta piedra, tres personas se ven envueltas en el destino de una nación. El inicio de la saga épica más ambiciosa de la fantasía contemporánea.",shortDesc:"El inicio de la saga épica más ambiciosa de Brandon Sanderson.",tags:["Magia","Política","Épico","Cosmos"]},
    {id:18,title:"Eragon",author:"Christopher Paolini",genre:"Fantasía",subgenre:"Fantasía épica",price:16.90,originalPrice:24.00,isbn:"0375826696",badge:"Fenómeno",rating:4.5,reviews:18234,pages:509,language:"Español",publisher:"Alfaguara",year:2003,color:"linear-gradient(135deg,#2a4a20 0%,#0a1808 100%)",description:"En la tierra de Alagaësia, el joven granjero Eragon encuentra un extraño huevo azul que resulta ser el huevo de un dragón. Se convierte en el primer Jinete de Dragón en una generación.",shortDesc:"El joven granjero que se convirtió en Jinete de Dragón.",tags:["Dragones","Aventura","Magia","Juvenil"]},
    {id:19,title:"Las crónicas de Narnia",author:"C.S. Lewis",genre:"Fantasía",subgenre:"Fantasía clásica",price:18.50,originalPrice:26.00,isbn:"0064471195",badge:"Clásico",rating:4.8,reviews:29876,pages:768,language:"Español",publisher:"Harper Collins",year:1950,color:"linear-gradient(135deg,#3a1a5c 0%,#120820 100%)",description:"A través de un armario mágico, los hermanos Pevensie descubren el mundo de Narnia, habitado por animales parlantes y criaturas fantásticas dominado por la Bruja Blanca. Aslan los guiará en su destino.",shortDesc:"El armario mágico que abre la puerta al reino de Narnia.",tags:["Magia","Niños","Alegoría","Clásico"]},

    /* ── CIENCIA FICCIÓN (6) ── */
    {id:2,title:"Duna",author:"Frank Herbert",genre:"Ciencia Ficción",subgenre:"Space Opera",price:18.50,originalPrice:26.00,isbn:"0441013597",badge:"Clásico",rating:4.8,reviews:12654,pages:896,language:"Español",publisher:"Debolsillo",year:1965,color:"linear-gradient(135deg,#1a3a5c 0%,#050f1c 100%)",description:"Paul Atreides es trasladado con su familia al planeta desértico Arrakis, único lugar donde se produce la especia melange. Una obra monumental que explora la ecología, la religión y el destino.",shortDesc:"La obra maestra de la ciencia ficción. Política, ecología y destino.",tags:["Space Opera","Política","Desierto","Mesías"]},
    {id:4,title:"1984",author:"George Orwell",genre:"Ciencia Ficción",subgenre:"Distopía",price:14.90,originalPrice:22.00,isbn:"0451524934",badge:"Distopía",rating:4.8,reviews:22341,pages:388,language:"Español",publisher:"Debolsillo",year:1949,color:"linear-gradient(135deg,#1a1a1a 0%,#3d3d3d 100%)",description:"Winston Smith trabaja en el Ministerio de la Verdad. Vive en Oceanía, un estado totalitario donde el Gran Hermano lo vigila absolutamente todo. Una advertencia profética sobre el totalitarismo.",shortDesc:"La distopía definitiva sobre el control totalitario y la vigilancia.",tags:["Distopía","Totalitarismo","Política","Clásico"]},
    {id:10,title:"Fahrenheit 451",author:"Ray Bradbury",genre:"Ciencia Ficción",subgenre:"Distopía",price:15.50,originalPrice:21.00,isbn:"1451673310",badge:"Esencial",rating:4.7,reviews:16543,pages:256,language:"Español",publisher:"Debolsillo",year:1953,color:"linear-gradient(135deg,#8B3a10 0%,#2d0f04 100%)",description:"En un futuro donde los libros están prohibidos y los bomberos los queman, Guy Montag comienza a cuestionar su trabajo. Una obra visionaria sobre la censura y el pensamiento crítico.",shortDesc:"Una distopía esencial sobre la censura y el poder de los libros.",tags:["Distopía","Censura","Libros","Clásico"]},
    {id:20,title:"Fundación",author:"Isaac Asimov",genre:"Ciencia Ficción",subgenre:"Space Opera",price:17.90,originalPrice:25.00,isbn:"0553293354",badge:"Maestro",rating:4.8,reviews:19654,pages:296,language:"Español",publisher:"Debolsillo",year:1951,color:"linear-gradient(135deg,#1a2a4a 0%,#050a18 100%)",description:"El matemático Hari Seldon usa la psicohistoria para predecir la caída del Imperio Galáctico. Para reducir el período de barbarismo que seguirá, crea la Fundación.",shortDesc:"La matemática puede predecir el destino de toda la humanidad.",tags:["Galáctico","Política","Historia","Clásico"]},
    {id:21,title:"El marciano",author:"Andy Weir",genre:"Ciencia Ficción",subgenre:"Hard Science Fiction",price:18.90,originalPrice:26.00,isbn:"0804139021",badge:"Superventas",rating:4.8,reviews:22134,pages:369,language:"Español",publisher:"Planeta",year:2011,color:"linear-gradient(135deg,#5c2010 0%,#1a0803 100%)",description:"El astronauta Mark Watney es abandonado en Marte tras ser dado por muerto. Solo, con suministros para pocos meses, debe usar su ingenio y botánica para sobrevivir.",shortDesc:"Solo en Marte, la ciencia es la única forma de sobrevivir.",tags:["Marte","Supervivencia","Ciencia","Humor"]},
    {id:22,title:"Neuromante",author:"William Gibson",genre:"Ciencia Ficción",subgenre:"Cyberpunk",price:16.50,originalPrice:23.00,isbn:"0441569595",badge:"Cyberpunk",rating:4.5,reviews:11234,pages:288,language:"Español",publisher:"Minotauro",year:1984,color:"linear-gradient(135deg,#1a0a2e 0%,#060311 100%)",description:"Case, un hacker arruinado, recibe una misión extraordinaria: penetrar en una Inteligencia Artificial llamada Neuromante. La novela que fundó el género cyberpunk.",shortDesc:"La novela que inventó el ciberespacio y fundó el cyberpunk.",tags:["Cyberpunk","Hacker","IA","Futuro"]},

    /* ── THRILLER (6) ── */
    {id:23,title:"El código Da Vinci",author:"Dan Brown",genre:"Thriller",subgenre:"Thriller histórico",price:17.90,originalPrice:25.00,isbn:"0385504209",badge:"80M copias",rating:4.3,reviews:45678,pages:561,language:"Español",publisher:"Umbriel",year:2003,color:"linear-gradient(135deg,#2a1a0a 0%,#0a0603 100%)",description:"Robert Langdon es convocado al Louvre, donde aparece el cadáver del curador. La investigación lo lleva a descubrir una conspiración que podría destruir los cimientos del cristianismo.",shortDesc:"El thriller que convirtió el arte en un código secreto mortal.",tags:["Misterio","Historia","Arte","Conspiración"]},
    {id:24,title:"El silencio de los inocentes",author:"Thomas Harris",genre:"Thriller",subgenre:"Thriller psicológico",price:16.90,originalPrice:24.00,isbn:"0312924585",badge:"Icónico",rating:4.7,reviews:16543,pages:384,language:"Español",publisher:"DeBolsillo",year:1988,color:"linear-gradient(135deg,#1a1a2a 0%,#060608 100%)",description:"La agente del FBI Clarice Starling debe entrevistar al psiquiatra Hannibal Lecter para atrapar a un asesino en serie. Un duelo psicológico brillante y perturbador.",shortDesc:"El duelo psicológico que redefinió el thriller criminal.",tags:["Crimen","Psicología","FBI","Oscuro"]},
    {id:25,title:"Misery",author:"Stephen King",genre:"Thriller",subgenre:"Thriller de terror",price:15.90,originalPrice:22.00,isbn:"0451169522",badge:"Stephen King",rating:4.7,reviews:18765,pages:386,language:"Español",publisher:"DeBolsillo",year:1987,color:"linear-gradient(135deg,#1a0505 0%,#080101 100%)",description:"El escritor Paul Sheldon tiene un accidente. Annie Wilkes, su mayor fan, lo rescata y lo mantiene cautivo. Cuando descubre que Paul matará a su personaje favorito, se convierte en su pesadilla.",shortDesc:"Cuando tu mayor fan se convierte en tu peor pesadilla.",tags:["Terror","Secuestro","Claustrofóbico","King"]},
    {id:26,title:"La chica del tren",author:"Paula Hawkins",genre:"Thriller",subgenre:"Thriller psicológico",price:16.50,originalPrice:23.00,isbn:"1594634025",badge:"Bestseller",rating:4.2,reviews:32456,pages:395,language:"Español",publisher:"Planeta",year:2015,color:"linear-gradient(135deg,#1a1535 0%,#060512 100%)",description:"Rachel toma el mismo tren cada mañana. Cuando una mujer a la que observaba desaparece, se ve envuelta en la investigación. Un thriller sobre la memoria y el engaño.",shortDesc:"El tren que pasa cada día esconde un secreto mortal.",tags:["Psicológico","Suspense","Memoria","Secretos"]},
    {id:27,title:"Perdida",author:"Gillian Flynn",genre:"Thriller",subgenre:"Thriller psicológico",price:17.50,originalPrice:24.00,isbn:"0307588378",badge:"Fenómeno",rating:4.4,reviews:28934,pages:432,language:"Español",publisher:"Mondadori",year:2012,color:"linear-gradient(135deg,#2a1020 0%,#0a0308 100%)",description:"La mañana de su quinto aniversario de boda, Amy desaparece. Las pruebas apuntan a su esposo Nick, pero la historia tiene múltiples capas y engaños.",shortDesc:"El matrimonio perfecto que oculta algo absolutamente monstruoso.",tags:["Matrimonio","Manipulación","Giro","Suspense"]},
    {id:28,title:"El nombre de la rosa",author:"Umberto Eco",genre:"Thriller",subgenre:"Thriller histórico",price:19.90,originalPrice:28.00,isbn:"0156001314",badge:"Literario",rating:4.7,reviews:12345,pages:502,language:"Español",publisher:"Lumen",year:1980,color:"linear-gradient(135deg,#1a1200 0%,#070500 100%)",description:"En la Edad Media, el monje Guillermo de Baskerville investiga misteriosas muertes en una abadía benedictina. La pista lleva a un libro prohibido de Aristóteles.",shortDesc:"Un monje medieval resuelve un misterio en una abadía laberíntica.",tags:["Medieval","Misterio","Filosofía","Historia"]},

    /* ── LITERATURA (8) ── */
    {id:3,title:"Cien años de soledad",author:"Gabriel García Márquez",genre:"Literatura",subgenre:"Realismo mágico",price:19.90,originalPrice:28.00,isbn:"0060883286",badge:"Premio Nobel",rating:4.9,reviews:15820,pages:471,language:"Español",publisher:"Harper Collins",year:1967,color:"linear-gradient(135deg,#2d5a27 0%,#0a1a08 100%)",description:"La historia de la familia Buendía a lo largo de siete generaciones en Macondo. Lo maravilloso y lo cotidiano conviven naturalmente en esta obra maestra del realismo mágico.",shortDesc:"La novela fundacional del realismo mágico latinoamericano.",tags:["Realismo mágico","Latinoamérica","Familia","Épico"]},
    {id:5,title:"El alquimista",author:"Paulo Coelho",genre:"Literatura",subgenre:"Novela filosófica",price:16.50,originalPrice:23.00,isbn:"0062315005",badge:"65M copias",rating:4.7,reviews:19876,pages:208,language:"Español",publisher:"Harper Collins",year:1988,color:"linear-gradient(135deg,#8b6f2e 0%,#2d2008 100%)",description:"Santiago, un joven pastor andaluz, sueña con un tesoro en Egipto y decide seguir su Leyenda Personal. La novela en portugués más traducida de la historia.",shortDesc:"La alegoría más vendida del mundo sobre los sueños y el destino.",tags:["Filosofía","Viaje","Espiritualidad","Sueños"]},
    {id:6,title:"La sombra del viento",author:"Carlos Ruiz Zafón",genre:"Literatura",subgenre:"Novela gótica",price:20.90,originalPrice:30.00,isbn:"0143034901",badge:"Superventas",rating:4.8,reviews:9654,pages:576,language:"Español",publisher:"Planeta",year:2001,color:"linear-gradient(135deg,#2a1a3a 0%,#0d0815 100%)",description:"Barcelona, 1945. Daniel Sempere descubre en el Cementerio de los Libros Olvidados que alguien está destruyendo todas las obras de un autor maldito. Un misterio apasionante.",shortDesc:"Un laberinto de misterio y pasión en la Barcelona de posguerra.",tags:["Misterio","Barcelona","Historia","Gótico"]},
    {id:11,title:"Crimen y castigo",author:"Fiódor Dostoyevski",genre:"Literatura",subgenre:"Novela psicológica",price:17.90,originalPrice:25.00,isbn:"0140449138",badge:"Clásico ruso",rating:4.8,reviews:11234,pages:576,language:"Español",publisher:"Alianza",year:1866,color:"linear-gradient(135deg,#1a1535 0%,#080610 100%)",description:"Raskolnikov planea el asesinato de una anciana usurera creyéndose por encima de la moral. La novela sigue su desintegración psicológica atormentado por la culpa.",shortDesc:"La obra maestra de Dostoyevski sobre la culpa y la redención.",tags:["Psicológico","Rusia","Culpa","Filosofía"]},
    {id:12,title:"El gran Gatsby",author:"F. Scott Fitzgerald",genre:"Literatura",subgenre:"Novela modernista",price:13.90,originalPrice:20.00,isbn:"0743273567",badge:"Clásico EE.UU.",rating:4.5,reviews:18750,pages:208,language:"Español",publisher:"Alianza",year:1925,color:"linear-gradient(135deg,#1a3a2a 0%,#050f08 100%)",description:"Nueva York, años veinte. El misterioso millonario Jay Gatsby da fiestas legendarias para reconquistar a su amor del pasado. Una crítica mordaz al sueño americano.",shortDesc:"La crítica definitiva al sueño americano en los locos años veinte.",tags:["Sueño americano","Años 20","Romance","Clásico"]},
    {id:13,title:"Orgullo y prejuicio",author:"Jane Austen",genre:"Literatura",subgenre:"Novela romántica",price:14.50,originalPrice:20.00,isbn:"0141439513",badge:"Inmortal",rating:4.8,reviews:24567,pages:432,language:"Español",publisher:"Penguin",year:1813,color:"linear-gradient(135deg,#3a1a2a 0%,#0f0509 100%)",description:"Elizabeth Bennet y el señor Darcy protagonizan el romance más célebre de la literatura universal. Una novela irónica sobre las convenciones sociales y el amor verdadero.",shortDesc:"El romance más célebre de la literatura universal.",tags:["Romance","Inglaterra","Ironía","Clásico"]},
    {id:14,title:"El señor de las moscas",author:"William Golding",genre:"Literatura",subgenre:"Novela alegórica",price:14.90,originalPrice:21.00,isbn:"0399501487",badge:"Premio Nobel",rating:4.6,reviews:12876,pages:290,language:"Español",publisher:"Alianza",year:1954,color:"linear-gradient(135deg,#2a1a0a 0%,#0a0603 100%)",description:"Un grupo de niños británicos queda atrapado en una isla desierta. La civilización se derrumba ante la violencia. Una alegoría sobre la naturaleza humana.",shortDesc:"Una perturbadora alegoría sobre la barbarie en la naturaleza humana.",tags:["Alegoría","Supervivencia","Naturaleza humana","Clásico"]},
    {id:16,title:"El proceso",author:"Franz Kafka",genre:"Literatura",subgenre:"Novela existencialista",price:13.50,originalPrice:19.00,isbn:"0805209999",badge:"Kafkiano",rating:4.6,reviews:9321,pages:256,language:"Español",publisher:"Alianza",year:1925,color:"linear-gradient(135deg,#1a1a1a 0%,#2d2d2d 100%)",description:"Josef K. se despierta y es detenido sin saber de qué crimen se le acusa. Intenta descubrir la verdad en una burocracia absurda. Una obra fundamental del existencialismo.",shortDesc:"La pesadilla burocrática que definió un adjetivo universal: kafkiano.",tags:["Existencialismo","Absurdo","Burocracia","Clásico"]},

    /* ── NO FICCIÓN (6) ── */
    {id:8,title:"Sapiens",author:"Yuval Noah Harari",genre:"No Ficción",subgenre:"Historia",price:21.50,originalPrice:30.00,isbn:"0062316095",badge:"Fenómeno",rating:4.7,reviews:28943,pages:512,language:"Español",publisher:"Debate",year:2011,color:"linear-gradient(135deg,#0f3a4a 0%,#04151c 100%)",description:"¿Cómo llegó el Homo sapiens a dominar el planeta? Harari recorre 70,000 años de historia humana con una visión fascinante y provocadora.",shortDesc:"La historia de la humanidad contada de forma completamente nueva.",tags:["Historia","Humanidad","Ciencia","Evolución"]},
    {id:29,title:"Homo Deus",author:"Yuval Noah Harari",genre:"No Ficción",subgenre:"Futurología",price:22.50,originalPrice:31.00,isbn:"0062464310",badge:"Continuación",rating:4.6,reviews:17654,pages:448,language:"Español",publisher:"Debate",year:2015,color:"linear-gradient(135deg,#1a0a2e 0%,#050310 100%)",description:"Después de conquistar el hambre y la guerra, Harari explora la búsqueda de la inmortalidad y la posibilidad de convertirnos en dioses mediante la IA.",shortDesc:"¿Qué hará la humanidad cuando supere el hambre y la muerte?",tags:["Futuro","IA","Humanidad","Filosofía"]},
    {id:30,title:"Pensar rápido, pensar despacio",author:"Daniel Kahneman",genre:"No Ficción",subgenre:"Psicología cognitiva",price:23.90,originalPrice:33.00,isbn:"0374533555",badge:"Premio Nobel",rating:4.7,reviews:21456,pages:496,language:"Español",publisher:"Debate",year:2011,color:"linear-gradient(135deg,#0a1a3a 0%,#030710 100%)",description:"El Premio Nobel Kahneman revela los dos sistemas que rigen nuestro pensamiento: el rápido e intuitivo, y el lento y lógico. Muestra los sesgos de nuestras decisiones.",shortDesc:"Cómo los sesgos de nuestra mente nos llevan a decisiones irracionales.",tags:["Psicología","Economía","Decisiones","Ciencia"]},
    {id:31,title:"En busca de sentido",author:"Viktor Frankl",genre:"No Ficción",subgenre:"Psicología existencial",price:15.90,originalPrice:22.00,isbn:"0807014273",badge:"Imprescindible",rating:4.9,reviews:34567,pages:165,language:"Español",publisher:"Herder",year:1946,color:"linear-gradient(135deg,#2a2a10 0%,#0a0a03 100%)",description:"Basado en su experiencia en campos de concentración nazis, Frankl narra cómo los prisioneros con propósito tenían más probabilidades de sobrevivir.",shortDesc:"La experiencia en los campos nazis que fundó la logoterapia.",tags:["Psicología","Holocausto","Sentido","Supervivencia"]},
    {id:32,title:"El arte de la guerra",author:"Sun Tzu",genre:"No Ficción",subgenre:"Tratado clásico",price:12.90,originalPrice:18.00,isbn:"1590302257",badge:"2500 años",rating:4.6,reviews:29876,pages:96,language:"Español",publisher:"Trotta",year:"~500 a.C.",color:"linear-gradient(135deg,#2a1a0a 0%,#0a0603 100%)",description:"Escrito hace más de 2500 años, es el texto militar estratégico más influyente de la historia. Sus principios se aplican hoy en los negocios y la vida.",shortDesc:"El tratado estratégico más leído durante 2500 años.",tags:["Estrategia","Liderazgo","Clásico","China"]},
    {id:33,title:"Una breve historia del tiempo",author:"Stephen Hawking",genre:"No Ficción",subgenre:"Divulgación científica",price:19.90,originalPrice:27.00,isbn:"0553380168",badge:"10M copias",rating:4.7,reviews:25432,pages:212,language:"Español",publisher:"Crítica",year:1988,color:"linear-gradient(135deg,#0a1a3a 0%,#030710 100%)",description:"Hawking lleva al lector desde el Big Bang hasta los agujeros negros, pasando por la naturaleza del tiempo. El libro de divulgación científica más vendido de la historia.",shortDesc:"El viaje más vendido al corazón del universo y del tiempo.",tags:["Física","Cosmos","Agujeros negros","Hawking"]}
];

// ══ NOVEDADES (recientes) ═════════════════════════════════════════
const NEW_RELEASES = [
    {id:101,title:"Tomorrow, and Tomorrow",author:"Gabrielle Zevin",genre:"Ficción",price:21.50,isbn:"0593321200",color:"linear-gradient(135deg,#4a2060,#1a0830)",year:2024,pages:401,rating:4.6,reviews:3421,description:"Sam y Sadie crean un juego que revoluciona la industria. Una historia sobre creatividad, amor y el precio del éxito.",tags:["Contemporánea","Amistad","Arte"]},
    {id:102,title:"Intermezzo",author:"Sally Rooney",genre:"Ficción",price:19.90,isbn:"0374611998",color:"linear-gradient(135deg,#1a3a2a,#081510)",year:2024,pages:448,rating:4.4,reviews:2187,description:"Dos hermanos muy diferentes lidian con el duelo por su padre en la Irlanda contemporánea.",tags:["Contemporánea","Familia","Amor"]},
    {id:103,title:"James",author:"Percival Everett",genre:"Literatura",price:23.00,isbn:"0385550367",color:"linear-gradient(135deg,#3a1a0a,#150800)",year:2024,pages:320,rating:4.8,reviews:4562,description:"Premio Pulitzer 2024. Reimaginación de Huckleberry Finn narrada desde la perspectiva de Jim, el esclavo.",tags:["Premio Pulitzer","Historia","Libertad"]},
    {id:104,title:"The God of the Woods",author:"Lauren Fox",genre:"Thriller",price:20.50,isbn:"0593656844",color:"linear-gradient(135deg,#1a1a4a,#080820)",year:2024,pages:384,rating:4.3,reviews:1876,description:"En un campamento de verano, una adolescente desaparece. Una novela sobre secretos familiares y misterios enterrados.",tags:["Thriller","Misterio","Familia"]},
    {id:105,title:"Orbital",author:"Samantha Harvey",genre:"Ficción",price:18.50,isbn:"0802164056",color:"linear-gradient(135deg,#2a0a3a,#0f0015)",year:2024,pages:209,rating:4.5,reviews:2341,description:"Premio Booker 2024. Seis astronautas orbitan la Tierra durante 24 horas. Una meditación sobre la humanidad.",tags:["Premio Booker","Espacio","Filosófico"]},
    {id:106,title:"The Women",author:"Kristin Hannah",genre:"Literatura",price:22.00,isbn:"1250178630",color:"linear-gradient(135deg,#0a2a1a,#001008)",year:2024,pages:512,rating:4.7,reviews:6789,description:"Vietnam, 1965. Frances McGrath se alista como enfermera. Una historia sobre las mujeres olvidadas de la guerra.",tags:["Guerra","Histórica","Mujeres"]},
    {id:107,title:"All Fours",author:"Miranda July",genre:"Ficción",price:21.00,isbn:"1594634882",color:"linear-gradient(135deg,#2a1a0a,#100800)",year:2024,pages:352,rating:4.2,reviews:1543,description:"Una artista se detiene a 30 minutos de casa. Una novela sobre la identidad femenina, la maternidad y el deseo.",tags:["Contemporánea","Identidad","Mujer"]},
    {id:108,title:"The Anxious Generation",author:"Jonathan Haidt",genre:"No Ficción",price:24.00,isbn:"0593655036",color:"linear-gradient(135deg,#1a2a3a,#080f18)",year:2024,pages:385,rating:4.6,reviews:8234,description:"¿Por qué los índices de depresión juvenil se dispararon alrededor de 2012? Los smartphones causaron una crisis.",tags:["Psicología","Tecnología","Juventud"]}
];

// ══ FALLBACKS — libros adicionales si la API falla ════════════════
const EXTRA_BOOKS_FALLBACK = [
    {id:201,title:"Babel",author:"R.F. Kuang",genre:"Fantasía",subgenre:"Fantasía histórica",price:23.50,originalPrice:32.00,isbn:"0063021420",badge:"Premio Nebula",rating:4.6,reviews:24531,pages:545,language:"Español",publisher:"Hidra",year:2022,color:"linear-gradient(135deg,#3a2a10 0%,#0f0c04 100%)",description:"Oxford, 1836. Robin Swift es llevado del Cantón a Inglaterra para entrenar en el arte de la traducción mágica. Una crítica brillante al colonialismo británico.",shortDesc:"Magia, traducción y revolución en la Oxford colonial.",tags:["Magia","Historia","Colonialismo","Lenguaje"]},
    {id:202,title:"Proyecto Hail Mary",author:"Andy Weir",genre:"Ciencia Ficción",subgenre:"Hard Science Fiction",price:21.90,originalPrice:30.00,isbn:"0593135202",badge:"Bestseller 2021",rating:4.9,reviews:31245,pages:496,language:"Español",publisher:"Nova",year:2021,color:"linear-gradient(135deg,#1a3050 0%,#040c18 100%)",description:"Ryland Grace despierta solo en una nave espacial sin recordar su misión. Pronto descubre que la humanidad depende de él. Del autor de El Marciano.",shortDesc:"La misión imposible para salvar a la humanidad.",tags:["Espacio","Misterio","Primer contacto","Humor"]},
    {id:203,title:"La paciente silenciosa",author:"Alex Michaelides",genre:"Thriller",subgenre:"Thriller psicológico",price:18.50,originalPrice:25.00,isbn:"1250301696",badge:"Bestseller",rating:4.5,reviews:42765,pages:336,language:"Español",publisher:"Alfaguara",year:2019,color:"linear-gradient(135deg,#1a0a25 0%,#080310 100%)",description:"Alicia Berenson dispara cinco veces a su esposo y nunca vuelve a hablar. Un psicoterapeuta obsesionado con su caso intentará desentrañar la verdad.",shortDesc:"El silencio que esconde un crimen perfecto.",tags:["Psicológico","Crimen","Silencio","Giro"]},
    {id:204,title:"Klara y el Sol",author:"Kazuo Ishiguro",genre:"Literatura",subgenre:"Distopía literaria",price:19.90,originalPrice:27.00,isbn:"059331817X",badge:"Premio Nobel",rating:4.4,reviews:18923,pages:303,language:"Español",publisher:"Anagrama",year:2021,color:"linear-gradient(135deg,#3a3010 0%,#100c04 100%)",description:"Klara, una Amiga Artificial, observa el mundo desde el escaparate de una tienda esperando ser elegida. Una meditación sobre el amor y la conciencia.",shortDesc:"Una IA observa el mundo humano desde el escaparate.",tags:["IA","Distopía","Conciencia","Nobel"]},
    {id:205,title:"Cuatro mil semanas",author:"Oliver Burkeman",genre:"No Ficción",subgenre:"Filosofía práctica",price:17.50,originalPrice:24.00,isbn:"0374159122",badge:"Bestseller 2021",rating:4.5,reviews:14532,pages:288,language:"Español",publisher:"Salamandra",year:2021,color:"linear-gradient(135deg,#102a30 0%,#040c0e 100%)",description:"La vida humana es absurdamente corta: cuatro mil semanas. Burkeman propone un enfoque radical sobre el tiempo y la productividad.",shortDesc:"La vida es corta. La filosofía sobre cómo aprovecharla.",tags:["Tiempo","Productividad","Filosofía","Vida"]},
    {id:206,title:"El infinito en un junco",author:"Irene Vallejo",genre:"No Ficción",subgenre:"Historia de la cultura",price:20.50,originalPrice:28.00,isbn:"8417454966",badge:"Premio Nacional",rating:4.8,reviews:22341,pages:452,language:"Español",publisher:"Siruela",year:2019,color:"linear-gradient(135deg,#2a1a0a 0%,#0a0603 100%)",description:"La historia fascinante del libro como objeto, desde las tablillas sumerias hasta nuestros días. Un viaje por la cultura escrita.",shortDesc:"La historia del libro contada como una novela.",tags:["Historia","Libros","Cultura","Ensayo"]}
];
